version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - pip install requests -t .
      - zip -r lambda_function.zip .
      - aws lambda update-function-code --function-name OpenglotLambda --zip-file fileb://lambda_function.zip
artifacts:
  files:
    - lambda_function.zip